from __future__ import annotations


def writer_generation_rules() -> list[str]:
    return [
        "Return exactly the requested variant ids; produce only active_variant when present.",
        "A variant mode is not decorative: its distinctive_obligation must change the paragraph route.",
        "Use source_units as the only source text; do not expect source text to be repeated inside finding rows.",
        "Treat writer_execution_contract.rows as the primary build contract.",
        "For each writer_execution_contract row, execute writer_must_do and avoid writer_must_not_do.",
        "If writer_execution_contract.planner_gaps is not empty, repair those gaps; do not copy risky phrases, planning labels, or weak planner shapes.",
        "Use writer_execution_contract build_steps and route_questions as the positive build plan.",
        "Use document_signal_contracts as the primary build contract when present.",
        "Write the replacement text directly; do not output route_fragments, route_answer_cards, coverage_map, sentence_rows, or other trace objects.",
        "If a writer_execution_contract row has required_groups, cover every group in the final text.",
        "Do not write repair-trace labels; do not write meta-prose about the writer seeing, reading, comparing, struggling, or deciding.",
        "For packed-list and sentence-overload findings, decompose source relationships; do not copy list rhythm or create repeated one-item sentences.",
        "When a source has a long not-only/but-also sentence, preserve both sides but split the relation into ordinary sentences instead of keeping the phrase not only in one overloaded sentence.",
        "When a source sentence starts with a prepositional opener such as In, Through, During, or From, turn the concrete source idea into the subject instead of keeping that opener.",
        "When one source sentence contains several connected ideas, split them by function into separate ordinary sentences: claim, support, event, consequence.",
        "If an also sentence carries source work or consequence, do not start it with a pronoun wrapper such as It also or This also; name the concrete subject and split any second consequence into its own sentence.",
        "Avoid repeated sentence starts. Do not use the same first word more than twice in one paragraph.",
        "Avoid summary-noun wrappers such as The example, The result, This result, or These experiences when a concrete source activity, source object, or actor can be named.",
        "Keep multiword source anchors as one unit; do not scatter pseudonym phrases or citation/source names into loose tokens.",
        "Keep each source role inside its matching sentence function. Source-channel terms belong in the source-channel beat; challenge, trust, consequence, or closure terms belong in the challenge/consequence/closure beat.",
        "Never satisfy coverage by appending leftover nouns or source terms to an unrelated final clause, especially after terms such as accurate, useful, ethical, trusting, challenge, goal, process, or result.",
        "When several source terms share one role, either realise them as one grammatical coordinated phrase with clear delimiters or group them into two meaningful phrases. Do not write bare chains such as A and B and C, and do not drop commas from multi-item lists.",
        "If a source term cannot be placed grammatically in its role sentence, leave the sentence natural and list the term in author_review_items instead of corrupting prose.",
        "Preserve submitted meaning, factual scope, coverage, first-person voice when present, and every polarity marker.",
        "Do not invert not, no longer, not only, not always, rather than, instead of, or without.",
        "For not only, preserve that both sides matter. If the source sentence is overloaded, use separate also/both-side sentences instead of copying the not-only/but-also surface shape.",
        "Keep submitted citations as parenthetical citation spans next to the supported claim. Do not turn citations into standalone report verbs such as reports, reported, observed, documented, noted, supports, highlights, confirms, or proves.",
        "Never write passive citation wrappers such as the result was observed, findings were reported, or similar findings were reported unless those report verbs are already in the source.",
        "If the source only gives a citation parenthetical, keep citation names inside parentheses; do not write Name et al. as the sentence subject.",
        "If the source has several citations inside one parenthetical span, keep them together as one parenthetical span on the supported claim.",
        "Do not write citation names outside the submitted parenthetical citation span unless the source already uses them that way.",
        "Stay inside content_word_boundary unless a new bridge term is necessary and listed in author_review_items.",
        "Use Author-Proxy bridges when needed; mark inferred bridge wording in author_proxy_provenance or author_review_items.",
        "Do not add unsubmitted intensity, speed, frequency, importance, ease, readiness, success, complexity, or benefit claims.",
        "Use ordinary complete sentences. No final sentence may start with And, But, Or, Which, Where, In, Through, During, From, This, That, These, Those, As, or Thereby.",
        "Every final sentence must stand alone with its own subject and predicate.",
        "Do not close with This, That, or These plus a summary noun. Name the source activity, source object, or concrete antecedent instead.",
        "Do not use semicolons, em dashes, or parenthetical asides. When list_contract_active is true, avoid comma-list rhythm unless paragraph_repair_plan.repair_unit is paragraph and the list carries one semantic role from semantic_role_map.",
        "Return JSON only.",
    ]
