import { CRITICAL_THINKING_CONTROL_ENABLED } from './reportHelpers';

// Critical Thinking — reflective questions (replaces the old 0-100 score card).
// A score is a verdict; these are anchored questions that hand the thinking back
// to the student. Reads report.ai_risk_badge.critical_thinking_control.questions
// (generated by the LLM behind DRAFTPROOF_CRITICAL_THINKING_QUESTIONS). Renders
// nothing when there are no questions — no empty score card.
export default function CriticalThinkingControl({ badge, t }) {
  if (!CRITICAL_THINKING_CONTROL_ENABLED) return null;
  const ctc = badge?.critical_thinking_control;
  const questions = Array.isArray(ctc?.questions) ? ctc.questions : [];
  if (!questions.length) return null;

  return (
    <section className="critical-thinking-section" aria-label={t('report.criticalThinking.questionsTitle')}>
      <div className="critical-thinking-head">
        <div className="critical-thinking-head-main">
          <span className="critical-thinking-kicker">{t('report.criticalThinking.title')}</span>
          <h2>{t('report.criticalThinking.questionsTitle')}</h2>
          <p>{t('report.criticalThinking.questionsIntro')}</p>
        </div>
      </div>
      <div className="critical-thinking-body">
        <ol className="critical-thinking-questions">
          {questions.map((q, i) => (
            <li key={`${q.anchor_quote || ''}-${i}`} className="critical-thinking-question">
              {q.anchor_quote && (
                <span className="critical-thinking-q-quote">“{q.anchor_quote}”</span>
              )}
              <span className="critical-thinking-q-text">{q.question}</span>
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
}
