// allow-hardcode: human-crafted SEO landing-page copy + adaptable declaration templates (user-fill placeholders), not a scoring/matching oracle
export const aiDeclaration = {
  "eyebrow": "AI declaration",
  "title": "How to declare your AI use (with examples).",
  "lead": "More courses now ask you to acknowledge any AI tools you used. A clear declaration protects you and takes two minutes. Below are copy-paste templates you can adapt — patterned on common university acknowledgement formats.",
  "ctaPrimaryLabel": "Check your draft",
  "ctaSecondaryLabel": "See the content checker",
  "heroStat": {
    "label": "Best for",
    "value": "Disclosing AI use",
    "detail": "Short, specific, honest acknowledgements"
  },
  "intro": [
    {
      "title": "Why declare at all?",
      "body": "Disclosure turns did you use AI? from an accusation into a non-issue. It shows integrity, meets policies that increasingly require it, and protects you if your work is ever questioned."
    },
    {
      "title": "What to include",
      "body": "Three things: which tool you used, what you used it for, and (often) when. Keep it short and specific. Always state that you reviewed the output and take responsibility for the final work."
    }
  ],
  "sections": [
    {
      "eyebrow": "Copy-paste templates",
      "title": "Declaration examples you can adapt.",
      "lead": "Replace the bracketed parts. Your course's required wording always takes priority over a generic template.",
      "type": "templates",
      "items": [
        {
          "title": "General (Elsevier-style)",
          "body": "During the preparation of this work I used [TOOL] in order to [REASON]. After using this tool, I reviewed and edited the content as needed and take full responsibility for the content of this submission.",
          "note": "The most widely accepted format — adapt the bracketed parts."
        },
        {
          "title": "ChatGPT (planning support)",
          "body": "I acknowledge the use of ChatGPT (OpenAI, https://chat.openai.com) to brainstorm ideas and structure an outline for this assignment on [DATE]. All final text, analysis, and conclusions are my own.",
          "note": "Use when AI helped you plan, not write."
        },
        {
          "title": "Grammarly (editing only)",
          "body": "I acknowledge the use of Grammarly to check grammar, spelling, and clarity in this assignment. No content or arguments were generated by the tool.",
          "note": "For proofreading-only use."
        },
        {
          "title": "Microsoft Copilot",
          "body": "I acknowledge the use of Microsoft Copilot to summarise my own notes and to proofread my final draft. I reviewed all output and take full responsibility for the submitted work.",
          "note": "Patterned on common university acknowledgement examples."
        },
        {
          "title": "Research / summarising sources",
          "body": "I used [TOOL] to summarise sources I selected, on [DATE]. I verified each summary against the original source, and all citations are my own.",
          "note": "Stress that you verified — AI summaries can misstate sources."
        },
        {
          "title": "No AI used",
          "body": "No generative AI tools were used in the preparation of this assignment.",
          "note": "A clean declaration is also a declaration."
        }
      ]
    },
    {
      "eyebrow": "Getting it right",
      "title": "Common declaration mistakes.",
      "type": "cards",
      "items": [
        {
          "title": "Check your brief first",
          "body": "Some assessments require a specific format or a separate form. Your course's wording always overrides a generic template."
        },
        {
          "title": "Be specific, not vague",
          "body": "I used AI a bit helps no one. Name the tool and the task. Specificity reads as honesty."
        },
        {
          "title": "Don't over-declare to cover weak work",
          "body": "A declaration explains your process; it doesn't excuse ungrounded claims or fabricated citations. Fix the writing too."
        }
      ]
    }
  ],
  "linksEyebrow": "Keep reading",
  "linksTitle": "Related guides",
  "links": [
    {
      "label": "Academic integrity & AI",
      "to": "/academic-integrity-ai",
      "body": "Where AI use is fine — and where it isn't."
    },
    {
      "label": "What your Turnitin AI score means",
      "to": "/turnitin-ai-score",
      "body": "Reading the percentage honestly."
    },
    {
      "label": "Check your writing",
      "to": "/content-checker",
      "body": "Find weak grounding before you submit."
    }
  ],
  "ctaTitle": "Declared it? Now strengthen it.",
  "ctaBody": "A declaration covers your process. DraftProof checks the substance — citations, grounding, and AI-like passages — so the work stands on its own."
};
